AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.HelloWorldHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post

  PostMatrixMult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.MatrixHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /matrixmult
            Method: post
            
  Address:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.AddressHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        ListAddresses:
          Type: Api
          Properties:
            Path: /user/{user_id}/address
            Method: get
        CreateAddress:
          Type: Api
          Properties:
            Path: /user/{user_id}/address
            Method: post
        ReadAddress:
          Type: Api
          Properties:
            Path: /user/{user_id}/address/{id}
            Method: get
        UpdateAddress:
          Type: Api
          Properties:
            Path: /user/{user_id}/address/{id}
            Method: put
        DeleteAddress:
          Type: Api
          Properties:
            Path: /user/{user_id}/address/{id}
            Method: delete

  Email:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.EmailHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        ListEmails:
          Type: Api
          Properties:
            Path: /user/{user_id}/email
            Method: get
        CreateEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/email
            Method: post
        ReadEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/email/{id}
            Method: get
        UpdateEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/email/{id}
            Method: put
        DeleteEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/email/{id}
            Method: delete
            
  PhoneNumber:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.aws.codestar.projecttemplates.handler.PhoneNumberHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        ListEmails:
          Type: Api
          Properties:
            Path: /user/{user_id}/phone-number
            Method: get
        CreateEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/phone-number
            Method: post
        ReadEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/phone-number/{id}
            Method: get
        UpdateEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/phone-number/{id}
            Method: put
        DeleteEmail:
          Type: Api
          Properties:
            Path: /user/{user_id}/phone-number/{id}
            Method: delete